(function (global, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  else global.VAW_PACKAGE_EXPORTER = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';

  function crc32(bytes) {
    let crc = ~0;
    for (let i = 0; i < bytes.length; i += 1) {
      crc ^= bytes[i];
      for (let bit = 0; bit < 8; bit += 1) crc = (crc >>> 1) ^ (0xedb88320 & -(crc & 1));
    }
    return ~crc >>> 0;
  }
  function u16(value) { return [value & 255, (value >>> 8) & 255]; }
  function u32(value) { return [value & 255, (value >>> 8) & 255, (value >>> 16) & 255, (value >>> 24) & 255]; }
  function dosDateTime(date = new Date('2026-01-01T00:00:00Z')) {
    const year = Math.max(1980, date.getUTCFullYear());
    return { time: (date.getUTCHours() << 11) | (date.getUTCMinutes() << 5) | Math.floor(date.getUTCSeconds() / 2), day: ((year - 1980) << 9) | ((date.getUTCMonth() + 1) << 5) | date.getUTCDate() };
  }

  function encodeText(text) { return new TextEncoder().encode(String(text)); }
  function jsonEntry(name, value) { return { name, bytes: encodeText(JSON.stringify(value || null, null, 2) + '\n') }; }
  function textEntry(name, value) { return { name, bytes: encodeText(value) }; }

  function buildStoreZip(entries) {
    const encoder = new TextEncoder();
    const files = [];
    const central = [];
    let offset = 0;
    const { time, day } = dosDateTime();
    for (const entry of entries) {
      const nameBytes = encoder.encode(entry.name.replace(/\\/g, '/'));
      const dataBytes = entry.bytes instanceof Uint8Array ? entry.bytes : new Uint8Array(entry.bytes);
      const crc = crc32(dataBytes);
      const local = new Uint8Array([...u32(0x04034b50), ...u16(20), ...u16(0), ...u16(0), ...u16(time), ...u16(day), ...u32(crc), ...u32(dataBytes.byteLength), ...u32(dataBytes.byteLength), ...u16(nameBytes.byteLength), ...u16(0)]);
      files.push(local, nameBytes, dataBytes);
      central.push({ nameBytes, crc, size: dataBytes.byteLength, offset });
      offset += local.byteLength + nameBytes.byteLength + dataBytes.byteLength;
    }
    const centralStart = offset;
    const centralParts = [];
    for (const entry of central) {
      const header = new Uint8Array([...u32(0x02014b50), ...u16(20), ...u16(20), ...u16(0), ...u16(0), ...u16(time), ...u16(day), ...u32(entry.crc), ...u32(entry.size), ...u32(entry.size), ...u16(entry.nameBytes.byteLength), ...u16(0), ...u16(0), ...u16(0), ...u16(0), ...u32(0), ...u32(entry.offset)]);
      centralParts.push(header, entry.nameBytes);
      offset += header.byteLength + entry.nameBytes.byteLength;
    }
    const centralSize = offset - centralStart;
    const end = new Uint8Array([...u32(0x06054b50), ...u16(0), ...u16(0), ...u16(central.length), ...u16(central.length), ...u32(centralSize), ...u32(centralStart), ...u16(0)]);
    return new Blob([...files, ...centralParts, end], { type: 'application/zip' });
  }

  async function buildPackageEntries({ bundle, sidecar, manifest, prefix = 'asset' }) {
    const entries = [];
    for (const record of bundle.records) {
      entries.push({ name: `${prefix}/${record.normalizedPath}`, bytes: new Uint8Array(await record.file.arrayBuffer()) });
    }
    entries.push({ name: `${prefix}/${sidecar.assetId || 'asset'}.vaw.json`, bytes: encodeText(JSON.stringify(sidecar, null, 2) + '\n') });
    entries.push({ name: `${prefix}/VAW_ASSET_MANIFEST.json`, bytes: encodeText(JSON.stringify(manifest, null, 2) + '\n') });
    entries.push({ name: `${prefix}/README_IMPORT_PACKAGE.txt`, bytes: encodeText('Generated by VAW Blockbench Import Studio Workbench Hardening v0.6. Viewer/import status is separate from VAW readiness.\n') });
    return entries;
  }


  function normalizeEntryPath(value) {
    const raw = String(value || '').replace(/\\/g, '/').replace(/^\/+/, '').replace(/\/+/g, '/');
    const parts = [];
    for (const part of raw.split('/')) {
      if (!part || part === '.') continue;
      if (part === '..') parts.pop();
      else parts.push(part);
    }
    return parts.join('/');
  }

  function dirnameEntryPath(value) {
    const path = normalizeEntryPath(value);
    const parts = path.split('/');
    parts.pop();
    return parts.join('/');
  }

  function joinEntryPath(base, relative) {
    const b = normalizeEntryPath(base);
    const r = normalizeEntryPath(relative);
    return b ? normalizeEntryPath(`${b}/${r}`) : r;
  }

  function assetModelPaths(manifest) {
    return (manifest && Array.isArray(manifest.assets) ? manifest.assets : [])
      .map(asset => asset && asset.model && typeof asset.model.path === 'string' ? normalizeEntryPath(asset.model.path) : '')
      .filter(Boolean);
  }

  function findRecord(records, normalizedPath, manifestBasePath = '') {
    const wanted = normalizeEntryPath(normalizedPath).toLowerCase();
    const baseWanted = manifestBasePath ? joinEntryPath(manifestBasePath, normalizedPath).toLowerCase() : '';
    return records.find(record => {
      const actual = normalizeEntryPath(record.normalizedPath).toLowerCase();
      return actual === wanted || (baseWanted && actual === baseWanted);
    }) || null;
  }

  function pushUniqueEntry(entries, seen, name, bytes) {
    const normalizedName = normalizeEntryPath(name);
    const key = normalizedName.toLowerCase();
    if (seen.has(key)) return;
    seen.add(key);
    entries.push({ name: normalizedName, bytes });
  }

  async function buildVisualAssetPackEntries({ bundle, manifest, validation, projectFilesReport = null, textureReport = null, animationReport = null, dependencies = [], manifestBasePath = '', prefix = null } = {}) {
    if (!bundle || !bundle.records) throw new Error('Visual asset pack export requires a loaded bundle.');
    if (!manifest || manifest.format !== 'VAW_VISUAL_ASSET_PACK_V1') throw new Error('Visual asset pack export requires VAW_VISUAL_ASSET_PACK_V1 manifest.');
    const packPrefix = normalizeEntryPath(prefix || manifest.packId || 'visual_asset_pack');
    const entries = [];
    const seen = new Set();
    const modelPaths = assetModelPaths(manifest);
    const copiedRecords = [];

    // Engine-facing files must be written at manifest-relative paths. The loaded
    // browser folder may include an extra parent directory; that parent is not part
    // of the exported pack contract.
    for (const modelPath of modelPaths) {
      const modelRecord = findRecord(bundle.records, modelPath, manifestBasePath);
      if (!modelRecord) continue;
      pushUniqueEntry(entries, seen, `${packPrefix}/${modelPath}`, new Uint8Array(await modelRecord.file.arrayBuffer()));
      copiedRecords.push({ sourcePath: modelRecord.normalizedPath, packPath: modelPath, role: 'model' });

      const modelDir = dirnameEntryPath(modelPath);
      for (const dep of dependencies || []) {
        if (dep.status !== 'found' || !dep.path || !dep.uri || /^data:/i.test(dep.uri) || /^[a-z][a-z0-9+.-]*:/i.test(dep.uri)) continue;
        const depRecord = findRecord(bundle.records, dep.path, '');
        if (!depRecord) continue;
        const targetPath = joinEntryPath(modelDir, dep.uri);
        pushUniqueEntry(entries, seen, `${packPrefix}/${targetPath}`, new Uint8Array(await depRecord.file.arrayBuffer()));
        copiedRecords.push({ sourcePath: depRecord.normalizedPath, packPath: targetPath, role: dep.kind || 'dependency' });
      }
    }

    const sourceManifest = {
      note: 'Engine-facing package files are placed at manifest-relative paths. Exact loaded-file copies belong in Debug Package, not in source/.',
      loadedFiles: bundle.records.map(record => ({ path: record.normalizedPath, size: record.size, extension: record.extension })),
      manifestBasePath: manifestBasePath || '',
      manifestModelPaths: modelPaths,
      copiedEngineFiles: copiedRecords,
    };

    pushUniqueEntry(entries, seen, `${packPrefix}/VAW_VISUAL_ASSET_PACK_V1.json`, jsonEntry('x', manifest).bytes);
    pushUniqueEntry(entries, seen, `${packPrefix}/validation/VAW_VISUAL_ASSET_PACK_V1_VALIDATION_REPORT.json`, jsonEntry('x', validation || { packReady: false, diagnostics: [] }).bytes);
    pushUniqueEntry(entries, seen, `${packPrefix}/validation/PROJECT_FILES_REPORT.json`, jsonEntry('x', projectFilesReport || { summary: {}, files: [] }).bytes);
    pushUniqueEntry(entries, seen, `${packPrefix}/validation/TEXTURE_REPORT.json`, jsonEntry('x', textureReport || { summary: {}, images: [], materials: [], diagnostics: [] }).bytes);
    pushUniqueEntry(entries, seen, `${packPrefix}/validation/ANIMATION_REPORT.json`, jsonEntry('x', animationReport || { summary: {}, clips: [], warnings: [] }).bytes);
    pushUniqueEntry(entries, seen, `${packPrefix}/validation/GLTF_DEPENDENCY_REPORT.json`, jsonEntry('x', dependencies || []).bytes);
    pushUniqueEntry(entries, seen, `${packPrefix}/validation/LOADED_SOURCE_FILES_REPORT.json`, jsonEntry('x', sourceManifest).bytes);
    pushUniqueEntry(entries, seen, `${packPrefix}/README_VISUAL_ASSET_PACK.txt`, textEntry('x', [
      'VAW Visual Asset Pack V1',
      '',
      'This package is renderer-facing only.',
      'It must not define gameplay authority such as mass, force, collision, durability, Blueprint, CraftModel, or catalog data.',
      'VAW runtime should consume this through a registry/adapter and keep procedural visual fallback available.',
      '',
      'Important paths:',
      '- VAW_VISUAL_ASSET_PACK_V1.json: contract manifest',
      '- manifest.model.path: the model file path inside this package',
      '- validation/: export-time reports used to reproduce the Studio decision',
      '- validation/LOADED_SOURCE_FILES_REPORT.json: provenance of files loaded into Studio',
      '',
      'Debug Package, not Visual Asset Pack export, is the artifact for exact troubleshooting copies.',
      '',
    ].join('\n')).bytes);
    return entries;
  }

  async function buildDebugPackageEntries({ bundle, projectFilesReport, textureReport, viewerFacts, validation = null, dependencies = [], sidecarParseReport = null, animationReport = null, eventLog = [], sessionReport = null, prefix = 'vaw_debug_package' } = {}) {
    if (!bundle || !bundle.records) throw new Error('Debug package requires a loaded bundle.');
    const entries = [];
    for (const record of bundle.records) {
      entries.push({ name: `${prefix}/loaded_files/${record.normalizedPath}`, bytes: new Uint8Array(await record.file.arrayBuffer()) });
    }
    entries.push(jsonEntry(`${prefix}/PROJECT_FILES_REPORT.json`, projectFilesReport || { files: [] }));
    entries.push(jsonEntry(`${prefix}/TEXTURE_REPORT.json`, textureReport || { summary: {}, images: [], materials: [], meshes: [], diagnostics: [] }));
    entries.push(jsonEntry(`${prefix}/ANIMATION_REPORT.json`, animationReport || { summary: {}, clips: [], warnings: [] }));
    entries.push(jsonEntry(`${prefix}/GLTF_DEPENDENCY_REPORT.json`, dependencies || []));
    entries.push(jsonEntry(`${prefix}/SIDECAR_PARSE_REPORT.json`, sidecarParseReport || { recognizedPaths: [], invalidPaths: [], diagnostics: [] }));
    entries.push(jsonEntry(`${prefix}/VIEWER_FACTS.json`, viewerFacts || {}));
    entries.push(jsonEntry(`${prefix}/WORKBENCH_SESSION_REPORT.json`, sessionReport || { generatedBy: 'VAW Blockbench Import Studio', note: 'No session report supplied.' }));
    entries.push(jsonEntry(`${prefix}/VAW_READINESS_REPORT.json`, validation || { viewerOk: true, vawReady: false, diagnostics: [{ domain: 'debug-export', severity: 'info', code: 'vaw.notValidated', message: 'VAW readiness was not validated before debug export.' }] }));
    entries.push(textEntry(`${prefix}/EVENT_LOG.txt`, (eventLog || []).join('\n') + '\n'));
    entries.push(textEntry(`${prefix}/README_DEBUG_PACKAGE.txt`, [
      'VAW Blockbench Import Studio — Debug Package',
      '',
      'This package is for reproducing import/viewer problems.',
      'It is allowed even when VAW readiness fails or no sidecar exists.',
      '',
      'Contents:',
      '- loaded_files/: every file the user loaded into the studio',
      '- PROJECT_FILES_REPORT.json: model/buffer/texture/sidecar/unknown categories and used/unused/missing/ambiguous statuses',
      '- TEXTURE_REPORT.json: glTF image/material/mesh diagnostic and texture warnings',
      '- ANIMATION_REPORT.json: animation clips, channels, tracks and target warnings',
      '- GLTF_DEPENDENCY_REPORT.json: raw dependency resolver output',
      '- SIDECAR_PARSE_REPORT.json: loaded/invalid sidecar files and editor diagnostics',
      '- VIEWER_FACTS.json: renderer, camera, controls, bounds and model facts',
      '- WORKBENCH_SESSION_REPORT.json: high-level UI/session state',
      '- EVENT_LOG.txt: recent user/import/viewer events',
      '- VAW_READINESS_REPORT.json: readiness result if available, otherwise a not-validated note',
      '',
    ].join('\n')));
    return entries;
  }

  return Object.freeze({ buildStoreZip, buildPackageEntries, buildVisualAssetPackEntries, buildDebugPackageEntries, crc32 });
});
