#!/usr/bin/env node
'use strict';

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SOURCE_ROOTS = [path.join(ROOT, 'index.html'), path.join(ROOT, 'src')];
const OUTPUT = path.join(ROOT, 'tailwind.generated.css');
const TOKEN_PATTERN = /[!A-Za-z0-9_@:/.[\]#%(),+*'"=-]+/g;
const TOOL_VERSION = '4.1.10';

function filesUnder(target) {
  const stat = fs.statSync(target);
  if (stat.isFile()) return [target];
  return fs.readdirSync(target, { withFileTypes: true })
    .flatMap(entry => filesUnder(path.join(target, entry.name)))
    .filter(file => /\.(?:html|js)$/.test(file));
}

function collectCandidates() {
  const candidates = new Set();
  for (const file of SOURCE_ROOTS.flatMap(filesUnder)) {
    const text = fs.readFileSync(file, 'utf8');
    for (const match of text.matchAll(TOKEN_PATTERN)) {
      const token = match[0].replace(/^['"]|['"],?$/g, '');
      if (token && token.length <= 180 && !token.includes('://')) candidates.add(token);
    }
  }
  return [...candidates].sort();
}

function candidateDigest(candidates) {
  return crypto.createHash('sha256').update(candidates.join('\n')).digest('hex');
}

function existingDigest() {
  if (!fs.existsSync(OUTPUT)) return null;
  const match = fs.readFileSync(OUTPUT, 'utf8').match(/CANDIDATE_SHA256:\s*([a-f0-9]{64})/);
  return match?.[1] || null;
}

function resolveStylesheet(id, base) {
  let filename;
  if (id === 'tailwindcss') filename = require.resolve('tailwindcss/index.css');
  else if (id.startsWith('tailwindcss/')) filename = require.resolve(id);
  else filename = path.resolve(path.dirname(base || require.resolve('tailwindcss/index.css')), id);
  return { content: fs.readFileSync(filename, 'utf8'), base: filename };
}

(async () => {
  const candidates = collectCandidates();
  const digest = candidateDigest(candidates);
  if (process.argv.includes('--check')) {
    if (existingDigest() !== digest) {
      console.error(`tailwind.generated.css is stale: expected candidate hash ${digest}, found ${existingDigest() || 'none'}`);
      process.exit(1);
    }
    console.log(`tailwind.generated.css is current: ${candidates.length} candidates, ${digest}`);
    return;
  }

  let tailwind;
  try {
    tailwind = require('tailwindcss');
  } catch (error) {
    console.error(`Tailwind CSS ${TOOL_VERSION} is required only to regenerate tailwind.generated.css.`);
    console.error('Keep the checked-in generated file when that exact development tool is unavailable.');
    process.exit(2);
  }
  const installedVersion = require('tailwindcss/package.json').version;
  if (installedVersion !== TOOL_VERSION) throw new Error(`Tailwind version mismatch: expected ${TOOL_VERSION}, got ${installedVersion}.`);

  const compiler = await tailwind.compile('@import "tailwindcss";', { loadStylesheet: async (id, base) => resolveStylesheet(id, base) });
  const css = compiler.build(candidates);
  const header = `/* GENERATED by tools/generate_tailwind_css.js with Tailwind CSS ${TOOL_VERSION}\n * CANDIDATE_SHA256: ${digest}\n * Do not edit by hand.\n */\n`;
  fs.writeFileSync(OUTPUT, header + css, 'utf8');
  console.log(`${path.relative(ROOT, OUTPUT)}: ${candidates.length} candidates, ${Buffer.byteLength(css)} CSS bytes, ${digest}`);
})().catch(error => {
  console.error(error.stack || error);
  process.exit(1);
});
